### ISSUE TITLE
Filter Update Issue

### ISSUE THREAD

**Issue by UTADNCLab** [overlord1123/LowPassFilter#2]
```c++
float LowPassFilter::update(float input){
	return output += (input - output) * ePow;
}
``` 
![image](https://github.com/jimmyberg/LowPassFilter/assets/109170974/963cc114-39ce-46bc-b706-9af2f6081f69)

According to the equation in Wikipedia, in the filter update function, should it be output =  input + (output - input) * ePow;

**Comment by jimmyberg** [comment]
Hello @UTADNCLab,
Note that `ePow(1-exp(-iDeltaTime * 2 * M_PI * iCutOffFrequency))`. I did not find your reference, but it looks like `beta = exp(-iDeltaTime * 2 * M_PI * iCutOffFrequency)`. Expanding the equation in the lib, the formula is actually y[n]=y[n-1] + (x[n] - y[n-1]) * (1-beta), resulting in (indeed) y=(y[n-a]-x[n])*beta+x[n]. So the formula remains correct.

See my memo for complete derivation. 
[1st order digital low pass filter.pdf](https://github.com/jimmyberg/LowPassFilter/files/11965204/1st.order.digital.low.pass.filter.pdf)
